"""fix schema drift: campaign status constraint name, jsonb columns

Revision ID: ee0e282d11ae
Revises: d5e9f1a6c3b7
Create Date: 2026-10-07 17:51:34.445986

Milestone 26's own `migration-validation` CI job (`alembic check`) caught two pieces of drift
between `colt_db`'s models and the schema its own migrations had actually produced, both dating
from before `colt_db.base._NAMING_CONVENTION` existed:

- `CampaignModel`'s `CheckConstraint(..., name="valid_campaign_status")` passes its own explicit
  name, but `_NAMING_CONVENTION`'s `"ck"` key still formats it through
  `ck_%(table_name)s_%(constraint_name)s` — the model's own compiled name has always been
  `ck_campaigns_valid_campaign_status`, but the original migration (predating the convention)
  created the literal `valid_campaign_status`. Same constraint, cosmetically different name.
- `ConversationEventModel.event_metadata` and `SequenceStepModel.conditions` are declared
  `JSONB` on the model today, but their original migrations emitted generic `JSON` — picked up
  by whatever alembic/SQLAlchemy version first autogenerated them before the model was changed
  to `JSONB` (CLAUDE.md §9's "no model change without a matching migration" rule, broken once,
  silently, until this milestone's own CI started checking for it).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ee0e282d11ae"
down_revision: str | None = "d5e9f1a6c3b7"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint(op.f("valid_campaign_status"), "campaigns", type_="check")
    op.create_check_constraint(
        op.f("ck_campaigns_valid_campaign_status"),
        "campaigns",
        "status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED')",
    )
    op.alter_column(
        "conversation_events",
        "event_metadata",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "sequence_steps",
        "conditions",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )


def downgrade() -> None:
    op.alter_column(
        "sequence_steps",
        "conditions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.alter_column(
        "conversation_events",
        "event_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.drop_constraint(op.f("ck_campaigns_valid_campaign_status"), "campaigns", type_="check")
    op.create_check_constraint(
        op.f("valid_campaign_status"),
        "campaigns",
        "status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED')",
    )
